[build]
  base = "."
  command = "npm run build"
  publish = "build"

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--legacy-peer-deps"
  DISABLE_ESLINT_PLUGIN = "true"
  CI = "false"

[[redirects]]
  from = "/api/*"
  to = "http://64.227.103.13:4444/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
